ManagerCenter/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ManagerCenter import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^ChangePassword/$', views.change_password, name='ChangePassword'),
    url(r'^detail/$', views.account_detail, name='account_detail'),
    url(r'^accounts/login/$', views.acc_login, name='acc_login'),
    url(r'^accounts/logout/$', views.acc_logout, name='acc_logout'),
    url(r'^configCenter/', include('configCenter.urls')),
]

configCenter/urls.py
from django.conf.urls import url
from configCenter import views


urlpatterns = [
    url(r'^menulevel1/$', views.menuLv1, name='menuLv1_index'),
    url(r'^menulevel1/add/$', views.menuLv1_add, name='menuLv1_add'),
    url(r'^menulevel1/(\d+)/change/$', views.menuLv1_change, name='menuLv1_change'),
    url(r'^menulevel2/$', views.menuLv2, name='menuLv2_index'),
    url(r'^menulevel2/add/$', views.menuLv2_add, name='menuLv2_add'),
    url(r'^menulevel2/(\d+)/change/$', views.menuLv2_change, name='menuLv2_change'),
    url(r'^role/$', views.role_index, name='role_index'),
    url(r'^role/add/$', views.role_add, name='role_add'),
    url(r'^role/(\d+)/change/$', views.role_change, name='role_change'),
    url(r'^account/$', views.account_index, name='account_index'),
    url(r'^account/add/$', views.account_add, name='account_add'),
    url(r'^account/(\d+)/change/$', views.account_change, name='account_change'),
    url(r'^(\w+)/delete/$', views.delete_obj, name='delete_obj'),
    url(r'^account/(\d+)/reset_password/$', views.reset_password, name='reset_password'),
    url(r'^(\w+)/(\d+)/$', views.not_found),
]

configCenter/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, PermissionsMixin, AbstractBaseUser
)


# Create your models here.

class AccountManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        创建普通账号
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        建管理员账号
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=32)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    roles = models.ManyToManyField('Role', blank=True)

    objects = AccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        #     "Does the user have a specific permissions?"
        #     # Simplest possible answer: Yes, always
        if self.is_admin:
            # print('我是管理员')
            return True
        else:
            # 不是管理员
            app_name = self._meta.app_label
            for db_perm in self.get_all_permissions():
                if '%s.%s' % (app_name, perm) == db_perm:
                    return True
            return False

    #
    def has_module_perms(self, app_label):
        if self.is_admin:
            # print('我是管理员')
            return True
        else:
            return False

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_active

    class Meta:
        verbose_name = '账号表'
        verbose_name_plural = verbose_name
        permissions = (
            ('menuLv1_index_get', '配置中心一级索引页面'),
            ('menuLv2_index_get', '配置中心二级索引页面'),
            ('role_index_get', '配置中心角色索引页面'),
            ('account_index_get', '配置中心账号索引页面'),
            ('menuLv1_add_all', '配置中心一级菜单添加页面'),
            ('menuLv1_change_all', '配置中心一级菜单修改页面'),
            ('menuLv2_add_all', '配置中心二级菜单添加页面'),
            ('menuLv2_change_all', '配置中心二级菜单修改页面'),
            ('role_add_all', '配置中心角色添加页面'),
            ('role_change_all', '配置中心角色修改页面'),
            ('account_add_all', '配置中心账号添加页面'),
            ('account_change_all', '配置中心账号修改页面'),
            ('delete_obj_post', '配置中心删除提交页面'),
            ('reset_password_post', '配置中心账号密码修改提交页面'),
        )


class Role(models.Model):
    ''' 角色表 '''
    name = models.CharField(max_length=32, unique=True)
    menu_level1 = models.ManyToManyField('MenuLevel1', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '角色表'
        verbose_name_plural = '角色表'


class MenuLevel1(models.Model):
    '''一级菜单'''
    name = models.CharField(max_length=32, unique=True)
    url_type_choices = ((0, 'alias'), (1, 'absolute_url'))
    url_type = models.SmallIntegerField(choices=url_type_choices, default=0,
                                        help_text='注意：当一级菜单内包含二级菜单时，添加一级菜单要用absolute_url，url_name使用：#')
    url_name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '一级菜单表'
        verbose_name_plural = verbose_name


class MenuLevel2(models.Model):
    '''二级菜单'''
    name = models.CharField(max_length=32, unique=True)
    url_name = models.CharField(max_length=64, unique=True)
    level2_to_level1 = models.ForeignKey('MenuLevel1')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '二级菜单表'
        verbose_name_plural = verbose_name

templates/account_detail.html
{% extends 'index.html' %}
{% load  config_tags %}

{% block container %}
    <div class="panel">
        <div class="panel-body">
            <div class="bootstrap-table">
                <div class="fixed-table-container">
                    <div class="fixed-table-body">
                        <table id="demo-custom-toolbar" class="demo-add-niftycheck table table-striped">
                            <thead>
                            <tr>
                                <th colspan="2"><h3 class="text-center">当前账户详细信息</h3></th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for field in form_obj %}
                                <tr style="vertical-align: middle;">
                                    <td style="vertical-align: middle;">{{ field.label }}</td>
                                    <td style="vertical-align: middle;">{% account_detail field %}</td>
                                </tr>
                               {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>总控台</title>
    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/bootstrap.min.css" rel="stylesheet">
    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/nifty.min.css" rel="stylesheet">
    <!--Font Awesome [ OPTIONAL ]-->
    <link href="/static/plugin/nifty/css/font-awesome.min.css" rel="stylesheet">
    <!-- Create your own class to load custum image [ SAMPLE ]-->
    <!--SCRIPT-->
    <!--=================================================-->
    <!--Page Load Progress Bar [ OPTIONAL ]-->
    {#    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">#}
    <link href="/static/plugin/nifty/css/pace.min.css" rel="stylesheet">
    <script src="/static/plugin/nifty/js/pace.min.js"></script>
    <link id="theme" href="/static/plugin/nifty/css/themes/type-b/theme-ocean.min.css" rel="stylesheet">
    {% block css %}{% endblock %}

</head>
<body class="nifty-ready  pace-done">
<div id="container" class="effect mainnav-lg">
    <header id="navbar">
        <div id="navbar-container" class="boxed">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">
                    <div class="brand-title">
                        <span class="brand-text" style="display: inline-block;letter-spacing:10px;font-size:25px;">运维中心</span>
                    </div>
                </a>
            </div>
            <!--Navbar Dropdown-->
            <!--================================-->
            <div class="navbar-content clearfix">
                {% block header %}{% endblock %}
            </div>
            <!--================================-->
            <!--End Navbar Dropdown-->

        </div>
    </header>
    <!--===================================================-->
    <!--END NAVBAR-->
    <div class="boxed">
        <!--CONTENT CONTAINER-->
        <!--===================================================-->
        <div id="content-container">
            {% block container %}内容{% endblock %}


        </div>

        <!--===================================================-->
        <nav id="mainnav-container">
            <div id="mainnav">

                <!--Menu-->
                <!--================================-->
                <div id="mainnav-menu-wrap" style="margin-top: 0px;">
                    <div class="nano">
                        <div class="nano-content">
                            <ul id="mainnav-menu" class="list-group">
                                <!--Menu list item-->
                                {% block menu_left %}

                                {% endblock %}
                                <!--Menu list item-->
                            </ul>

                        </div>
                    </div>
                </div>
                <!--================================-->
                <!--End menu-->

            </div>
        </nav>

    </div>

</div>


<!--jQuery [ REQUIRED ]-->
<script src="/static/plugin/nifty/js/jquery-2.1.1.min.js"></script>
<!--BootstrapJS [ RECOMMENDED ]-->
<script src="/static/plugin/nifty/js/bootstrap.min.js"></script>
<!--Fast Click [ OPTIONAL ]-->
<script src="/static/plugin/nifty/js/fastclick.min.js"></script>
<!--Nifty Admin [ RECOMMENDED ]-->
<script src="/static/plugin/nifty/js/nifty.min.js"></script>
{#<script src="/static/bootstrap/js/bootstrap.js"></script>#}
{% block js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block header %}
    <div class="modal fade" tabindex="-1" role="dialog" tag="reset_password" style="display: none;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">修改账号密码</h4>
                </div>
                <div class="modal-body">
                    <form tag='reset_password' class="form-horizontal" method="POST">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">账号</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">email</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="inputPassword" name="password1"
                                       placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <lable for="inputPassword" class="col-sm-2 control-label">Password confirmation</lable>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="inputPassword2" name="password2"
                                       placeholder="Password confirmation">
                            </div>
                            <span style="color:grey"></span>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" onclick="close_reset_windows()">Close</button>
                            <button type="button" class="btn btn-primary" onclick="SavePassword()">Save changes</button>
                        </div>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


    <ul class="nav navbar-top-links pull-left">
        <!--Navigation toogle button-->
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <li class="tgl-menu-btn">
            <a class="mainnav-toggle" href="#">
                <i class="fa fa-navicon fa-lg"></i>
            </a>
        </li>
    </ul>
    <ul class="nav navbar-top-links pull-right">
        <li id="dropdown-user" class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle text-right" aria-expanded="false">
                <span class="pull-right">
                    <img class="img-circle img-user media-object" src="/static/img/av1.png"
                         alt="Profile Picture">
                </span>
                <div class="username hidden-xs">{{ request.user.name }}</div>
            </a>

            <div class="dropdown-menu dropd own-menu-md dropdown-menu-right with-arrow panel-default">

                <!-- User dropdown menu -->
                <ul class="head-list">
                    <li>
                        <a href="{% url 'account_detail' %}">
                            <i class="fa fa-user fa-fw fa-lg"></i> Profile
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="badge badge-danger pull-right">x</span>
                            <i class="fa fa-envelope fa-fw fa-lg"></i> Messages
                        </a>
                    </li>
                    <li>
                        <a onclick="ChangePassword()">
                            <i class="fa fa-gear fa-fw fa-lg"></i>修改密码
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-question-circle fa-fw fa-lg"></i> Help
                        </a>
                    </li>
                </ul>

                <!-- Dropdown footer -->
                <div class="pad-all text-right">
                    <a href="{% url 'acc_logout' %}" class="btn btn-primary">
                        <i class="fa fa-sign-out fa-fw"></i> Logout
                    </a>
                </div>
            </div>
        </li>
    </ul>

{% endblock %}

{% block menu_left %}
    {% for role in request.user.roles.all %}
        {% for m_lv1 in role.menu_level1.all %}
            {% if m_lv1.url_type == 0 %}
                <li class="active-link">
                    <a href="{% url m_lv1.url_name %}">
                        <i class="fa fa-dashboard"></i>
                        <span class="menu-title">
                        <strong>{{ m_lv1.name }}</strong>
                    </span>
                    </a>

                </li>
            {% else %}
                <li class="active-link">
                    <a href="{{ m_lv1.url_name }}">
                        <i class="fa fa-dashboard"></i>
                        <span class="menu-title">
                        <strong>{{ m_lv1.name }}</strong>
                    </span>
                    </a>
                    <ul class="collapse" aria-expanded="false" style="height: 0px;">
                        {% for m_lv2 in m_lv1.menulevel2_set.all %}
                            <li><a href="{% url m_lv2.url_name %}">{{ m_lv2.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}

{% block container %}
    右侧内容
{% endblock %}

{% block js %}
    <script>

        function CheckAllToggle(ele) {
            if ($(ele).prop("checked")) {
                $("input[tag='obj_checkbox']").prop("checked", true);
            } else {
                $("input[tag='obj_checkbox']").prop("checked", false);
            }
        }

        function ActionSubmit(form_ele) {
            var selected_ids = [];
            $("input[tag='obj_checkbox']:checked").each(function () {
                selected_ids.push($(this).val());
            });
            var selected_action = $('#action_list').val();
            if (selected_ids.length == 0) {
                alert("no object got selected");
                return
            }
            if (!selected_action) {
                alert("no action got selected");
                return
            }

            // start submit
            var selected_ids_ele = "<input name='selected_ids' type='hidden' value='" + selected_ids.toString() + "' >"
            $(form_ele).append(selected_ids_ele);
            return ture
        }

        function DeleteData() {
            var select_id = [];
            $("input[tag='obj_checkbox']:checked").each(function () {
                select_id.push($(this).val());
            })
            if (select_id.length == 0) {
                alert('请选择删除的数据')
            }
            $.ajax({
                url: "{{ request.path }}delete/",
                type: 'POST',
                data: {'delete_id': select_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                dataType: 'JSON',
                traditional: true,
                success: function (args) {
                    if (args == 'ok') {
                        location.reload()
                    }
                }

            })
        }

        function SetPassword(id, acct_email) {
            $('div[tag="reset_password"]').addClass('in');
            $('div[tag="reset_password"]').css('display', 'block');
            $('form[tag="reset_password"]').attr('active', '{{ request.path }}' + id + '/reset_password/')
            $('p').each(function () {
                if ($(this).text() == 'email') {
                    $(this).text(acct_email)
                }
            })
        }
        function close_reset_windows() {
            $('div[tag="reset_password"]').removeClass('in');
            $('div[tag="reset_password"]').css('display', 'none');
            window.location.reload(true);
        }

        function SavePassword() {
            $.ajax({
                url: $('form[tag="reset_password"]').attr('active'),
                type: 'POST',
                dataType: 'JSON',
                async: false,
                data: $('form[tag="reset_password"]').serialize(),
                success: function (args) {
                    if (args.status == 1) {
                        alert(args.message);
                        location.reload()
                    } else {
                        alert(args.error)
                    }
                }
            })
        }

        function ChangePassword() {
            $('div[tag="reset_password"]').addClass('in');
            $('div[tag="reset_password"]').css('display', 'block');
            $('form[tag="reset_password"]').attr('active', '/ChangePassword/');
            $('p').each(function () {
                if ($(this).text() == 'email') {
                    $(this).text('{{ request.user }}')
                }
            })
        }
    </script>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>系统登录</title>

    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/bootstrap.min.css" rel="stylesheet">


    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/nifty.min.css" rel="stylesheet">


</head>
<body class="nifty-ready  pace-done">
<div class="pace  pace-inactive">
    <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
        <div class="pace-progress-inner"></div>
    </div>
    <div class="pace-activity"></div>
</div>
<div id="container" class="cls-container">

    <!-- BACKGROUND IMAGE -->
    <!--===================================================-->
    <div id="bg-overlay" class="bg-img img-balloon"
         style="background-image:url('/static/plugin/nifty/img/sky.jpg')"></div>


    <!-- HEADER -->
    <!--===================================================-->
    <div class="cls-header cls-header-lg">
        <div class="cls-brand">
            <h1 class="error-code text-warning" style="margin-top:50%;">自动化运维系统</h1>
        </div>
    </div>
    <!--===================================================-->


    <!-- LOGIN FORM -->
    <!--===================================================-->
    <div class="cls-content">
        <div class="cls-content-sm panel">
            <div class="panel-body">
                <p class="pad-btm">系统登录页面</p>
                <form action="{% url 'acc_login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-user"></i></div>
                            <input type="email" class="form-control" placeholder="E-mail" name="logname">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
                            <input type="password" class="form-control" placeholder="Password" name="passwd">
                        </div>
                    </div>
                    <button class="btn btn-primary btn-lg btn-block" type="submit">
                        <i class="fa fa-facebook fa-fw"></i> 登  录
                    </button>
                    <span style="color:red">{{ errors.error }}</span>
                </form>
            </div>
        </div>
    </div>
    <!--===================================================-->

</div>

<!--jQuery [ REQUIRED ]-->
<script src="/static/plugin/nifty/js/jquery-2.1.1.min.js"></script>

<!--BootstrapJS [ RECOMMENDED ]-->
<script src="/static/plugin/nifty/js/bootstrap.min.js"></script>

<!--Fast Click [ OPTIONAL ]-->
{#	<script src="plugins/fast-click/fastclick.min.js"></script>#}

<!--Nifty Admin [ RECOMMENDED ]-->
<script src="/static/plugin/nifty/js/nifty.min.js"></script>

</body>
</html>

templates/pages-404.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404</title>

    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/bootstrap.min.css" rel="stylesheet">


    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/nifty.min.css" rel="stylesheet">
  <!--SCRIPT-->
    <!--Page Load Progress Bar [ OPTIONAL ]-->
    <link href="/static/plugin/nifty/plugins/pace/pace.min.css" rel="stylesheet">
    <script src="/static/plugin/nifty/plugins/pace/pace.min.js"></script>
</head>

<body>
	<div id="container" class="cls-container">
		
		<!-- HEADER -->
		<!--===================================================-->
		<div class="cls-header">
			<div class="cls-brand">
				<a class="box-inline" href="index.html">
					<!-- <img alt="Nifty Admin" src="images/logo.png" class="brand-icon"> -->
					<span class="brand-title">错误页面</span>
				</a>
			</div>
		</div>
		
		<!-- CONTENT -->
		<!--===================================================-->
		<div class="cls-content">
			<h1 class="error-code text-warning">没有权限</h1>
			<p class="h4 text-thin pad-btm mar-btm">
				<i class="fa fa-exclamation-circle fa-fw"></i>
				Sorry, 您没有访问当前页面的权限
			</p>

			<br>
			<div class="pad-top"><a class="btn-link" href="{% url 'index' %}">Back to Homepage</a></div>
		</div>
		
		
	</div>

	<!--jQuery [ REQUIRED ]-->
	<script src="/static/plugin/nifty/js/jquery-2.1.1.min.js"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="/static/plugin/nifty/js/bootstrap.min.js"></script>


	<!--Fast Click [ OPTIONAL ]-->
	<script src="/static/plugin/nifty/plugins/fast-click/fastclick.min.js"></script>

	
	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="/static/plugin/nifty/js/nifty.min.js"></script>


</body>
</html>

templates/pages-nofound.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404</title>

    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/bootstrap.min.css" rel="stylesheet">


    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="/static/plugin/nifty/css/nifty.min.css" rel="stylesheet">
  <!--SCRIPT-->
    <!--Page Load Progress Bar [ OPTIONAL ]-->
    <link href="/static/plugin/nifty/plugins/pace/pace.min.css" rel="stylesheet">
    <script src="/static/plugin/nifty/plugins/pace/pace.min.js"></script>
</head>

<body>
	<div id="container" class="cls-container">
		
		<!-- HEADER -->
		<!--===================================================-->
		<div class="cls-header">
			<div class="cls-brand">
				<a class="box-inline" href="index.html">
					<!-- <img alt="Nifty Admin" src="images/logo.png" class="brand-icon"> -->
					<span class="brand-title">页面不存在</span>
				</a>
			</div>
		</div>
		
		<!-- CONTENT -->
		<!--===================================================-->
		<div class="cls-content">
			<h1 class="error-code text-warning">NOT FOUND</h1>
			<p class="h4 text-thin pad-btm mar-btm">
				<i class="fa fa-exclamation-circle fa-fw"></i>
				Sorry, 您访问的当前页面不存在
			</p>

			<br>
			<div class="pad-top"><a class="btn-link" href="{% url 'index' %}">Back to Homepage</a></div>
		</div>
		
		
	</div>

	<!--jQuery [ REQUIRED ]-->
	<script src="/static/plugin/nifty/js/jquery-2.1.1.min.js"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="/static/plugin/nifty/js/bootstrap.min.js"></script>


	<!--Fast Click [ OPTIONAL ]-->
	<script src="/static/plugin/nifty/plugins/fast-click/fastclick.min.js"></script>

	
	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="/static/plugin/nifty/js/nifty.min.js"></script>


</body>
</html>